version: '3.8'

services:
  micro-user:
    build:
      context: ./micro-user
    env_file:
      - ./micro-user/.env
    ports:
      - 8080:50051
    volumes:
      - .:/app
      - /app/node_modules
      - /protos
